In [1]:
import torch
import numpy as np

/home/chenyang/software/miniconda3/envs/pytorch/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
b = torch.rand((3,2))
b

tensor([[0.5363, 0.9324],
        [0.2271, 0.9266],
        [0.4768, 0.6183]])

In [4]:
c,d = torch.chunk(b, chunks=2)

In [5]:
c

tensor([[0.5363, 0.9324],
        [0.2271, 0.9266]])

In [6]:
d

tensor([[0.4768, 0.6183]])

In [7]:
c,d = torch.chunk(b, chunks=2, dim=1)

In [8]:
c

tensor([[0.5363],
        [0.2271],
        [0.4768]])

In [9]:
d

tensor([[0.9324],
        [0.9266],
        [0.6183]])

torch.gather实际上是针对某个维度，根据index矩阵来选择该维度上应选择输入矩阵中对应维度的哪个元素放到输出矩阵对应位置

In [10]:
t = torch.tensor([[1,2], [3,4]])

In [11]:
# dim = 0, 代表竖着看, [1, 0]表示1,3中选3，2,4中选2
torch.gather(t, 0, torch.tensor([[1, 0], [1, 0]]))

tensor([[3, 2],
        [3, 2]])

scatter表示针对设定的dim，我们根据index矩阵确定要放入的下标

In [12]:
src = torch.arange(1, 11).reshape((2, 5))
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [17]:
index = torch.tensor([[0,1,2,0,1], [1,2,0,1,2]])

In [18]:
torch.zeros(3, 5, dtype = src.dtype).scatter_(0, index, src)

tensor([[ 1,  0,  8,  4,  0],
        [ 6,  2,  0,  9,  5],
        [ 0,  7,  3,  0, 10]])

In [19]:
a = torch.arange(10).reshape(5, 2)

In [20]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [22]:
torch.split(a, 3)

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[6, 7],
         [8, 9]]))

In [25]:
torch.split(a, [2,3])

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7],
         [8, 9]]))

In [26]:
b = torch.zeros((3,2))
a = torch.ones((3,2))

In [27]:
torch.stack([a, b])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [28]:
torch.stack([a, b]).shape

torch.Size([2, 3, 2])

In [29]:
torch.stack([a, b], dim = 1)

tensor([[[1., 1.],
         [0., 0.]],

        [[1., 1.],
         [0., 0.]],

        [[1., 1.],
         [0., 0.]]])

In [30]:
torch.stack([a, b], dim = 1).shape

torch.Size([3, 2, 2])