In [2]:
import torch
import numpy as np

/home/chenyang/software/miniconda3/envs/pytorch/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
a = np.random.randn(2,3)
a

array([[-0.88253408,  0.1872785 , -1.05672692],
       [-0.78252879, -1.67860838, -0.97358931]])

In [5]:
b = torch.tensor(a)
b

tensor([[-0.8825,  0.1873, -1.0567],
        [-0.7825, -1.6786, -0.9736]], dtype=torch.float64)

In [6]:
torch.from_numpy(a)

tensor([[-0.8825,  0.1873, -1.0567],
        [-0.7825, -1.6786, -0.9736]], dtype=torch.float64)

In [7]:
c = torch.ones_like(b)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [8]:
d = torch.zeros_like(b)
d

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [9]:
torch.rand_like(b)

tensor([[0.9291, 0.3239, 0.8463],
        [0.0451, 0.4269, 0.1416]], dtype=torch.float64)

In [10]:
torch.rand((2,2))

tensor([[0.3538, 0.9863],
        [0.9370, 0.8904]])

In [11]:
torch.rand([2,2])

tensor([[0.7966, 0.0853],
        [0.2864, 0.4510]])

In [14]:
b.dtype

torch.float64

In [15]:
b.shape

torch.Size([2, 3])

In [16]:
b.device

device(type='cpu')

In [17]:
torch.is_tensor(a)

False

In [18]:
torch.is_tensor(b)

True

In [19]:
a = torch.tensor(1.0)

In [20]:
torch.is_nonzero(a)

True

In [21]:
a = torch.tensor(0)

In [22]:
torch.is_nonzero(a)

False

In [23]:
b

tensor([[-0.8825,  0.1873, -1.0567],
        [-0.7825, -1.6786, -0.9736]], dtype=torch.float64)

In [24]:
torch.numel(b)

6

In [25]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [26]:
torch.arange(0,5,2)

tensor([0, 2, 4])

In [28]:
torch.range(0, 5)

/home/chenyang/software/miniconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([0., 1., 2., 3., 4., 5.])

In [29]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
torch.eye(5,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [32]:
torch.full((2,3), 5.)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [35]:
torch.full_like(b, 5)

tensor([[5., 5., 5.],
        [5., 5., 5.]], dtype=torch.float64)

In [39]:
a = torch.rand((2,2))
a

tensor([[0.1508, 0.4573],
        [0.5875, 0.0293]])

In [40]:
b = torch.rand((2,3))
b

tensor([[0.6204, 0.1891, 0.1217],
        [0.9790, 0.4003, 0.0216]])

In [41]:
torch.cat([a,b], dim=1)

tensor([[0.1508, 0.4573, 0.6204, 0.1891, 0.1217],
        [0.5875, 0.0293, 0.9790, 0.4003, 0.0216]])